"""LLM call using Langchain."""

from langchain_core.language_models.chat_models import BaseChatModel

from config.llm_model import LLM_MODEL


def run(llm: BaseChatModel) -> None:
    """Run the example."""
    llm_response = llm.invoke("What is Physics?")  # AIMessage object

    # The text generated by the model in response to the prompt
    print("Content:", llm_response.content)
    print("=" * 50)

    # Provider-specific metadata (e.g. model name, stop reason, timing)
    print("Response metadata:", llm_response.response_metadata)
    print("=" * 50)

    # Token counts for the prompt, completion, and total
    print("Usage metadata:", llm_response.usage_metadata)
    print("=" * 50)

    # LangChain serialization attributes used for reproducibility
    print("LC attributes:", llm_response.lc_attributes)
    print("=" * 50)


if __name__ == "__main__":
    run(LLM_MODEL)
