"""LLM call using Langchain and Ollama."""

from langchain_ollama import ChatOllama


def run() -> None:
    """Run the example."""
    llm = ChatOllama(model="llama3.2")
    llm_response = llm.invoke("What is Physics?")  # AIMessage object

    # The text generated by the model in response to the prompt
    print("Content:", llm_response.content)
    print("=" * 50)

    # Provider-specific metadata (e.g. model name, stop reason, timing)
    print("Response metadata:", llm_response.response_metadata)
    print("=" * 50)

    # Token counts for the prompt, completion, and total
    print("Usage metadata:", llm_response.usage_metadata)
    print("=" * 50)

    # LangChain serialization attributes used for reproducibility
    print("LC attributes:", llm_response.lc_attributes)
    print("=" * 50)


if __name__ == "__main__":
    run()
